name: build

on:
  - push
  - pull_request

jobs:
  
  docker-dev:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build . -f dev.Dockerfile

  platform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build . -f platform.Dockerfile